//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotasEstudiante
    {
        public int iDAlumno { get; set; }
        public string Alumno { get; set; }
        public Nullable<decimal> lab1 { get; set; }
        public Nullable<decimal> lab2 { get; set; }
        public Nullable<decimal> lab3 { get; set; }
        public Nullable<decimal> par1 { get; set; }
        public Nullable<decimal> par2 { get; set; }
        public Nullable<decimal> par3 { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
